### PR TITLE
Add google calendars where the user has write access

### PR DESCRIPTION
**Pull request by surfing**
Add google calendars where the user has write access but is not the owner.
This gives access to all shared google calendars where the user has full access.
See #36

### CODE REVIEW

**Comment by chriadam** [comment]
LGTM.  I wonder whether we should provide UI during account-creation phase which lets the user select which calendars they wish to sync?  But for now, I think this is fine.

@antseppa @pvuorela any concerns?

**Comment by pvuorela** [comment]
No concerns on my side. Good to have this.

For selecting calendars, in case user disables some in the Calendar app, is the unnecessary traffic really that much it would matter? In case we actually want to disable syncing for some, maybe that could be connected to enabled visibility.

**Comment by surfing** [comment]
After this patch I can try to implement calendars with read access only. Is this a feature you would accept, too?

**Comment by chriadam** [comment]
Read-only can be tricky to get right due to strange semantics enforced by mkcal.  E.g., if a notebook is marked as read-only, and you attempt to add a new (synced) event to it, the event will be inserted into the database with a null notebook field, effectively becoming an immediate orphan event.

I have no issue with you implementing the feature - it would be useful.  However, I would need to be convinced that it doesn't accidentally introduce some subtle bugs in some codepath, before I'd accept it into the repo.

**Comment by surfing** [comment]
okay, so I think I will first try to add some tests to this project and afterwards some to the mkcal project. I think there is no other way to convince you.

**Comment by chriadam** [comment]
Thank you very much, that would be great appreciated!

**Comment by palikao** [comment]
I agree, shared calendars are needed, at list only view mode.

**Pull request merged**
